# EMBEDDED SERVER CONFIGURATION (ServerProperties)
#server:
#    port: 9000
#    address:  # bind to a specific NIC
#    session-timeout:  # session timeout in seconds
#    context-parameters.*:  # Servlet context init parameters, e.g. server.context-parameters.a=alpha
#    context-path:  # the context path, defaults to '/'
#    jsp-servlet.class-name: org.apache.jasper.servlet.JspServlet # The class name of the JSP servlet
#    jsp-servlet.init-parameters.*:  # Init parameters used to configure the JSP servlet
#    jsp-servlet.registered: true # Whether or not the JSP servlet is registered
#    servlet-path:  # the servlet path, defaults to '/'
#    display-name: xxx # the display name of the application
server:
    port: 20001
    session:
        cookie:
            name: CRAWLSESSION

#spring.view.prefix: templates

#shell.command-path-patterns= # classpath*:/commands/**, classpath*:/crash/commands/**
shell:
    auth:
        simple:
            user:
                name: donopo
                password: 123
    ssh:
        port: 20002
#    command-path-patterns: classpath*:/cmd/** #defalut /commands/**,/crash/commands/**



hello: hello

---
spring:
    profiles: home
thriftServerPort: 20003

---
spring:
    profiles: dev
thriftServerPort: 20003

---
spring:
    profiles: stable
thriftServerPort: 20003
